### PR TITLE
Build update, added missed props, fixed dropdown

### PR DESCRIPTION
**Pull request by asvetliakov**
Summary:
* Use es6 export for modules (both element names and elements/collections/modules/etc.. objects are exported)
* Fixed webpack configuration. Use correct external definitions and export library target. Added sourcemap (previous devtool option was misspelled)
* Updated main point to dist/semantic-react.js, no reason to keep it to server.js
* Added few missed props (Docs were also regenerated)
* Changed react-outsideclickhandler to react-onclickoutside. The first one installs react-0.13 which is not good if you're using 0.14 in project
* Fixed dropdown, instead ruining your dropdown work as in https://github.com/hallister/semantic-react/pull/30 request

### CODE REVIEW

**Comment by aphofstede** [comment]
@asvetliakov Could you add an example to the docs for Dropdown and DropdownMenu maybe?

**Comment by asvetliakov** [comment]
This commit doesn't include DropdownMenu. Going to send pull request for it (and may be for other stuff) if author accepts this one.
Also current doc generation is buggy - it couldn't annotate example code for decorated component now

**Comment by aphofstede** [comment]
Do you think the docs code should handle your new component's set-up, or is the fact that the example code displays it badly (I saw the functions all get printed out etc.) a sign that your component changes are not in line with the envisioned architecture of semantic-react? :)

**Comment by asvetliakov** [comment]
it's not in the line of current arch, it's the just the problem in example generating. And i don't see anything wrong in HOC/decorator pattern, most of react components/libraries are utilizing it anyway.
Will try to fix doc generating :)

**Comment by aphofstede** [comment]
Awesome! Note: I just rebased to your branch; working off of that now. Great work, hope we can see some of those changes trickle back into the main. @hallister Do you need smaller PRs? Are they too massive to review in a reasonable time frame?

**Comment by hallister** [comment]
Going to merge this. The build up of PR's was mostly due to being on a Ember project at work. I should get to the other PR's soon.

**Pull request merged**
