### PR TITLE
Add view component: Statistic, Statistics

### PR DESCRIPTION
**Pull request by zitsen**
Not completed:
* ~~props support for simple value/label~~

Done, wait for reviews.

### CODE REVIEW

**Comment by asvetliakov** [comment]
Thank you for contribution! In the first view it looks very good
Could you add shouldComponentUpdate() with shallowCompare to new classes so they could skip re-render when necessary? (Looks like they couldn't be functional because getChildContext())

I'll evaluate more tomorrow

**Comment by zitsen** [comment]
Did you mean 	49ed9be @asvetliakov ?

**Comment by zitsen** [comment]
Ready at my side.

**Comment by zitsen** [comment]
Added documents

**Comment by asvetliakov** [comment]
Looks very good!
Few moments:
1. Can you add corresponding classes to https://github.com/hallister/semantic-react/blob/master/src/styleguide/StyleGuide.jsx ?
2. Can you make Value as statefull component with shallowCompare() ? I'm going to remove all functional component usages in lib according to #112

**Comment by asvetliakov** [comment]
Great! Thank you!

**Pull request merged**
