### PR TITLE
Table examples

### PR DESCRIPTION
**Pull request by aphofstede**
Added a couple of table examples to the docs.
This PR includes @	asvetliakov's fix for the dropdown as well as some minor property fixes.
Please note the FIXMEs and TODOs in the example tables and comment on whether to apply them or not?

### CODE REVIEW

**Comment by hallister** [comment]
Can you rebase this?

**Comment by aphofstede** [comment]
Done. It became a bit of a mess though, many changes from @asvetliakov included in this one. @hallister want me to cherry pick the Table example changes into a new branch and create a new PR or something?

**Comment by asvetliakov** [comment]
@aphofstede 
Can you take a look into new react-styleguidist docs?

**Comment by aphofstede** [comment]
OK, got it working. Had to fight npm a bit though; had to npm install estraverse-fb, react-styleguidist and babel-preset-react-hmre separately. Then start it with `npm run styleguide-server`.
Played around with a divider component example. Things like markdown block-quotes don't seem to work well though..?
I would further say we need to pimp the style a little bit; very bare-bones at the moment :)

**Comment by aphofstede** [comment]
Will create a new PR

**Pull request closed without merging**
