### PR TITLE
Multiple fixes and improvements

### PR DESCRIPTION
**Pull request by jimmyn**

### CODE REVIEW

**Comment by asvetliakov** [comment]
Thank you for great contribution!
Few questions:
1) What is allowAdditions in select and what purpose does it serve?
2) Reducing precision for modal is fine, but performance doesn't depend on this too much. react-motion re-renders modal many time with interpolated style values, so performance depends on user-side code and how child elements are structured. I'd suggest to avoid any func binding or list rendering operations in animated elements and use shouldComponentUpdate() for child elements.
Better to use separate component for whole modal body, but it's not possible with current markup. 
Also there are few this.func.bind(this) in modal examples so this may cause performance hit too.

**Comment by jimmyn** [comment]
1) The same as in [Semantic UI docs](http://semantic-ui.com/modules/dropdown.html#/examples). gives users the ability to add their own options
2) I needed close animation, so mostly it's not about performance.

Great job actually. So far it's the best semantic ui port to React.

**Comment by asvetliakov** [comment]
@jimmyn Can you show your selects?
Animation may be really bad when menu items are being rerendered during motion interpolation. Make sure that you're not creating new objects for each ```<Option>```

**Comment by asvetliakov** [comment]
@jimmyn can you update also typings in index.d.ts for new select props/callback changes ?

**Comment by jimmyn** [comment]
This is my DropDownMenu component

```jsx
import React, {PropTypes, Component} from 'react';
import DropDownMenu from 'semantic-react/lib/modules/dropdown/dropdownmenu';

class DropDown extends Component {
  constructor(props) {
    super(props);
    this.state = {
      active: false
    };
  }

  onDropDownClick = () => {
    this.setState({
      active: !this.state.active
    });
  };

  closeDropDown = () => {
    this.setState({
      active: false
    });
  };

  render() {
    return (
      <DropDownMenu
        active={this.state.active}
        onClick={this.onDropDownClick}
        onRequestClose={this.closeDropDown}
        {...this.props}>
        {this.props.children}
      </DropDownMenu>
    );
  }
}

export default DropDown;
```

And I use it line this (with react-router `Link` instead of `Option`)

```jsx
    <DropDownMenu className="item labeled icon floating" label="Billing">
      <Link to="/profile/billing_info" className="item" activeClassName="active">
        Billing info
      </Link>
      <Link to="/profile/billing_history" className="item" activeClassName="active">
        Billing history
      </Link>
    </DropDownMenu>

```

**Comment by asvetliakov** [comment]
The problem that is ```<Link>``` component is not pure.
The menu is animating transition is being re-rerendered about 60 times for each element when opening/closing.
Try this:
```
<MenuItem component={Link} to="/profile/billing_info"> 
```
MenuItem contains shouldComponentUpdate with shallowEqual check to this should guard agains unnecessary rerenders.

I'd also use browserHistory.push instead ```<Link>``` and use controlled menu (put your to to as menuValue and use onMenuChange/onMenuClick callback for menu)

**Pull request merged**
