### PR TITLE
Table examples styleguidist-style

### PR DESCRIPTION
**Pull request by aphofstede**
Including fixes for missing properties etc.

### CODE REVIEW

**Comment by aphofstede** [comment]
@asvetliakov Re-did them! Please check it out and merge if agreed.

**Comment by asvetliakov** [comment]
@aphofstede Thanks
Can you modify tests for touched properties? (i.e. for button, image, menu).
Also these components should consume properties (the tests should check that)
To run tests type npm run test:watch or test:watch:win

Also replace describe.only with describe in modules/dropdown/__tests__ (i forgot to remove them)

**Comment by asvetliakov** [comment]
need another rebase :smile:

**Comment by aphofstede** [comment]
@asvetliakov Sure. Weird merge in there, but I think it's ok.

**Comment by aphofstede** [comment]
This one needs some test additions/modifications too though

**Comment by aphofstede** [comment]
HOC?

**Comment by asvetliakov** [comment]
Higher order component
```
const IconButton = ({someCustomProp ...other}) => {
other.className = setAdditionalClassnames();
return (<Button {...other} someCustomProp/>);
}
```

**Comment by asvetliakov** [comment]
Yes, please add tests props tests to all components which has tests. Once it's started, it needs to be done.

**Comment by asvetliakov** [comment]
Oh, and it will be wonderful if you add missing props to semantic-react.d.ts

**Comment by aphofstede** [comment]
@asvetliakov Added tests, please review?

**Comment by aphofstede** [comment]
@asvetliakov Rebased, reverted IconButton, replaced Icon's left/right with a "pointing" prop, made eslint happy(er).
@Asgator Changed the working of Rating a bit so it retains its default active-Icons behaviour if you don't handle it from the onChange(). (return false if you handle it yourself) Also, prop was being used for state, changed back to use this.state again. (see link in comment) Agree?

**Comment by asvetliakov** [comment]
:+1: 
Will merge today

**Comment by aphofstede** [comment]
@asvetliakov Could you check the rating test? I couldn't get the clicks to work :/

**Comment by asvetliakov** [comment]
Sorry for delay, merging.
As for rating test - Rating component doesn't render Icon, it renders <i> directory, so wrapper.find(Icon) won't find anything

**Comment by aphofstede** [comment]
Part of this PR was that it renders Icons now.

**Comment by asvetliakov** [comment]
Ah, didn't notice, then you can try:
1) wrapper.find(Icon).at(0).shallow().simulate('click')
2) wrapper.find(Icon).at(0).prop("onClick")(val);

**Comment by aphofstede** [comment]
Those don't work either. I have no idea what's going on here :/
`console.log(JSON.stringify(wrapper.find(Icon).at(0).shallow().debug()));` reports:

    LOG LOG: '"<i className=\"icon link icon\" onClick={[Function]} />"'

and `console.log(JSON.stringify(wrapper.find(Icon).at(0).shallow().prop("onClick")));`:

    LOG LOG: undefined

**Comment by asvetliakov** [comment]
Try:
wrapper.find(Icon).at(0).prop(«onClick»)())
Without shallow()
shallow() does shallow rendering at specified component (one or more levels down), not needed in case of just accessing to child prop

**Comment by aphofstede** [comment]
Same result.

Here's some I've tried (with & without `.shallow()`)

            //wrapper.find(Icon).at(0).shallow().simulate('click')
            //wrapper.find(Icon).at(0).shallow().prop("onClick")();
            //wrapper.find(Icon).at(0).shallow().prop("onClick")(0);
            //wrapper.find(Icon).first().prop('onClick')();
            //wrapper.prop('onIconClick')(0);

**Pull request merged**
